# Generated by Django 2.1a1 on 2018-05-29 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.CharField(blank=True, max_length=200, null=True)),
                ('record_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Year', models.CharField(max_length=200)),
                ('Month', models.CharField(max_length=200)),
                ('Date', models.CharField(max_length=200)),
                ('Elevation', models.CharField(max_length=200)),
                ('Storage', models.CharField(max_length=200)),
                ('Presentage', models.CharField(max_length=200)),
                ('Power', models.CharField(max_length=200)),
                ('Energy', models.CharField(max_length=200)),
                ('Outlet', models.CharField(max_length=200)),
                ('Spill', models.CharField(max_length=200)),
                ('Inflow', models.CharField(max_length=200)),
                ('Rainfall', models.CharField(max_length=200)),
            ],
        ),
    ]
